### ISSUE TITLE
The Wire.beginTransmission() and Wire.endTransmission() should not be used together with Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [analogdevicesinc/Linduino#1]
In the files:
- Linduino/LTSketchbook/libraries/LT_I2C_Wire/LT_I2C_Wire.cpp
- Linduino/LTSketchbook/libraries/Adafruit_FT6206_Library/Adafruit_FT6206.cpp
- Linduino/LTSketchbook/libraries/QuikEval_EEPROM_Wire/QuikEval_EEPROM_Wire.cpp

the function Wire.requestFrom() is often used together with Wire.beginTransmission() and Wire.endTransmission().

Regardless which Wire library or which processor is used, that is not correct.

Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes) number 2 and 3.

**Comment by malavikasajikumar** [comment]
Thank you for pointing this out. We will have this fixed immediately.

**Comment by Koepel** [comment]
The new [Adafruit_FT6206.cpp](https://github.com/adafruit/Adafruit_FT6206_Library/blob/master/Adafruit_FT6206.cpp) at Adafruit has it fixed. But there are also a few changes to the code. That might have influence on the rest of your code.

**Comment by malavikasajikumar** [comment]
Fixed on Commit: 9e81d9d0069a4eb553788fa92f8ac9e21a583c4c
