### ISSUE TITLE
DC2259.ino  ADC/Memory Self Test ERROR

### ISSUE THREAD

**Issue by sebashb** [analogdevicesinc/Linduino#15]
In the file:
• Linduino/LTSketchbook/Part Number/6000/6811/DC2259/DC2259.ino

On the case 12 (Run the ADC/Memory Self Test) the second argument of the function LTC6811_run_cell_adc_st should be TOTAL_IC and not ADC_CONVERSION_MODE.

**Comment by malavikasajikumar** [comment]
Fixed in PR https://github.com/analogdevicesinc/Linduino/pull/20
