### ISSUE TITLE
LTC6811 Linduino code bug in open wire check FIX

### ISSUE THREAD

**Issue by sebashb** [analogdevicesinc/Linduino#16]
There is a bug in the Linduino code for the LTC6811 code in function LTC681x_run_openwire in file LTC681x.cpp. The function crates two cell_asic structures pullUp_cell_codes and pullDwn_cell_codes but does not initialises them.

Then the function LTC681x_run_openwire calls LTC681x_rdcv in which the for cycle runs until ic[0].ic_reg.num_cv_reg. The problem is that this value has not been initialise. Thus sending unpredictable messages to the LTC which leads to code crash because the function that senda messages expects an answer from the LTC.

To fix this bug the function LTC6811_init_reg_limits(total_ic,pullUp_cell_codes); and LTC6811_init_reg_limits(total_ic,pullDwn_cell_codes); should be called to initialise register sizes on the structures that have been created before calling LTC681x_rdcv.

P.S.: This have been tested in LTC6811-2 but I think that it should be a problem for all the other chips that use this code.

**Comment by malavikasajikumar** [comment]
Fixed in PR https://github.com/analogdevicesinc/Linduino/pull/20
