### ISSUE TITLE
unwanted ISOSPI reversal in LTC681X.CCP -bug

### ISSUE THREAD

**Issue by TLS1000** [analogdevicesinc/Linduino#32]
When daisy chaining two LTC6810 chips, and writing different DCC in the configuration registers, I observed (via reading the conf registers) the two configurations got swapped between the two chips.

The SPI direction got reversed, although I did not set the "isospi_reverse" boolean to true.

the library does some things without spi reversal, and others with reversal. This is because of bugs in the code. example:
`
for (uint8_t current_ic = 0; current_ic<total_ic; current_ic++)
	{

		if (ic->isospi_reverse == true)

		{

			c_ic = current_ic;

		}

		else

		{

			c_ic = total_ic - current_ic - 1;

		}

`

but when the isospi_reverse variable is false, you don't want to reverse the direction
problem is solved by changing all fragments above to:

`for (uint8_t current_ic = 0; current_ic<total_ic; current_ic++)

	{

		if (ic->isospi_reverse == false)         //true to false

		{

			c_ic = current_ic;

		}

		else

		{

			c_ic = total_ic - current_ic - 1;

		}`

**Comment by malavikasajikumar** [comment]
https://github.com/analogdevicesinc/Linduino/pull/34
